In [1]:
from linear_model import LinearRegression, LogisticRegression, OvRLogisticRegression

In [2]:
import numpy as np
np.random.seed(42)

def test_linear():
    print("--- Тест LinearRegression (SVD) ---")
    X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
    y = np.array([12, 17, 22, 27])
    
    model = LinearRegression()
    model.fit(X, y)
    
    test_X = np.array([[5, 6]])
    pred = model.predict(test_X)
    print(f"Предсказание для [5, 6]: {pred.flatten()[0]:.2f} (Ожидалось: 33.00)")
    print(f"Коэффициенты: {model.coef_.flatten()}, Смещение: {model.intercept_}\n")

def test_binary_logistic():
    print("--- Тест LogisticRegression (Бинарная) ---")
    X = np.array([[1, 1], [2, 1], [1, 2], [10, 10], [11, 10], [10, 11]])
    y = np.array([0, 0, 0, 1, 1, 1])
    
    model = LogisticRegression(max_iter=5000, lr=0.1)
    model.fit(X, y)
    
    test_X = np.array([[2, 2], [9, 9]])
    probs = model.predict_proba(test_X)
    preds = model.predict(test_X)
    
    print(f"Вероятности для [2,2] и [9,9]:\n{probs}")
    print(f"Классы: {preds.flatten()} (Ожидалось: [0, 1])\n")

def test_ovr_logistic():
    print("--- Тест OvRLogisticRegression (Многоклассовая) ---")
    X = np.array([
        [0, 0], [0, 1],    
        [5, 5], [5, 6],   
        [10, 0], [10, 1]  
    ])
    y = np.array([0, 0, 1, 1, 2, 2])
    
    model = OvRLogisticRegression(max_iter=2000, lr=0.2)
    model.fit(X, y)
    
    test_X = np.array([[1, 1], [5, 5], [9, 1]])
    preds = model.predict(test_X)
    probs = model.predict_proba(test_X)
    
    print(f"Предсказание классов: {preds} (Ожидалось: [0, 1, 2])")
    print(f"Матрица вероятностей (N x K):\n{probs}\n")

if __name__ == "__main__":
    test_linear()
    test_binary_logistic()
    test_ovr_logistic()

--- Тест LinearRegression (SVD) ---
Предсказание для [5, 6]: 32.00 (Ожидалось: 33.00)
Коэффициенты: [1. 4.], Смещение: [3.]

--- Тест LogisticRegression (Бинарная) ---
Вероятности для [2,2] и [9,9]:
[[0.98543526 0.01456474]
 [0.00513837 0.99486163]]
Классы: [0 1] (Ожидалось: [0, 1])

--- Тест OvRLogisticRegression (Многоклассовая) ---
Предсказание классов: [0 1 2] (Ожидалось: [0, 1, 2])
Матрица вероятностей (N x K):
[[8.13825213e-01 6.75545924e-02 2.44419470e-02]
 [2.62866710e-03 9.80039698e-01 1.17824963e-03]
 [9.25053835e-07 1.23223308e-02 9.94750002e-01]]

